using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace XFEExtension.NetCore.ServerInteractive.SourceGenerator;

/// <summary>
/// 次级入口点增量生成器
/// 用于自动生成IServerCoreStandardService的入口点字典
/// </summary>
[Generator]
public class EntryPointGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 找到所有标记了EntryPointAttribute的方法
        var methodDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateMethod(s),
                transform: static (ctx, _) => GetMethodForGeneration(ctx))
            .Where(static m => m is not null);

        // 按类分组
        var compilationAndMethods = context.CompilationProvider.Combine(methodDeclarations.Collect());

        // 生成源代码
        context.RegisterSourceOutput(compilationAndMethods,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateMethod(SyntaxNode node)
    {
        return node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0;
    }

    private static MethodInfo? GetMethodForGeneration(GeneratorSyntaxContext context)
    {
        var methodDeclaration = (MethodDeclarationSyntax)context.Node;
        var methodSymbol = context.SemanticModel.GetDeclaredSymbol(methodDeclaration);

        if (methodSymbol is null)
            return null;

        // 检查是否有EntryPointAttribute
        var entryPointAttribute = methodSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "EntryPointAttribute");

        if (entryPointAttribute is null)
            return null;

        // 获取Path参数
        var path = entryPointAttribute.ConstructorArguments.FirstOrDefault().Value?.ToString();
        if (string.IsNullOrEmpty(path))
            return null;

        // 检查是否为异步方法
        var isAsync = methodSymbol.IsAsync ||
                      (methodSymbol.ReturnType is INamedTypeSymbol returnType &&
                       returnType.Name == "Task");

        var containingType = methodSymbol.ContainingType;

        return new MethodInfo(
            containingType.ContainingNamespace.ToDisplayString(),
            containingType.Name,
            methodSymbol.Name,
            path!,
            isAsync
        );
    }

    private static void Execute(Compilation compilation, ImmutableArray<MethodInfo?> methods, SourceProductionContext context)
    {
        if (methods.IsDefaultOrEmpty)
            return;

        // 按类分组
        var methodsByClass = methods
            .Where(m => m is not null)
            .GroupBy(m => (m!.Namespace, m.ClassName));

        foreach (var group in methodsByClass)
        {
            var (namespaceName, className) = group.Key;
            var methodInfos = group.ToList();

            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine($@"// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace {namespaceName}
{{
    /// <summary>
    /// {className}的自动生成入口点字典部分类
    /// </summary>
    public partial class {className}
    {{
        /// <inheritdoc/>
        public Dictionary<string, Action> SyncEntryPoints {{ get; }} = new()
        {{");

            // 添加同步入口点
            foreach (var method in methodInfos.Where(m => !m!.IsAsync))
            {
                sourceBuilder.AppendLine($"            {{ \"{method!.Path}\", {method.MethodName} }},");
            }

            sourceBuilder.AppendLine($@"        }};

        /// <inheritdoc/>
        public Dictionary<string, Func<Task>> AsyncEntryPoints {{ get; }} = new()
        {{");

            // 添加异步入口点
            foreach (var method in methodInfos.Where(m => m!.IsAsync))
            {
                sourceBuilder.AppendLine($"            {{ \"{method!.Path}\", {method.MethodName} }},");
            }

            sourceBuilder.AppendLine(@"        };
    }
}");

            context.AddSource($"{className}.EntryPoints.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }
    }

    private class MethodInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string MethodName { get; }
        public string Path { get; }
        public bool IsAsync { get; }

        public MethodInfo(string namespaceName, string className, string methodName, string path, bool isAsync)
        {
            Namespace = namespaceName;
            ClassName = className;
            MethodName = methodName;
            Path = path;
            IsAsync = isAsync;
        }
    }
}
